version: '3.9'

services:
  web:
    build: ./app
    ports:
      - '80:3000'
    tty: true
    volumes:
      - ./app:/app
      - /app/node_modules
  db:
    build: ./db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: arm64v8/adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data:
